[general]
enable_notifs = true

[fileinfo]
whitelist = [  # if defined, only files from these directories will be scrobbled. Keep as [] to allow all.
	"/path/to/movies_folder",
	"/path/to/videos_folder",
	'D:\path\to\windows\folder'  # single quotes are important in windows paths due to '\' character
]

# example regexes (uncomment to activate). To test your custom regexes, try regex101.com
[fileinfo.include_regexes]  # custom regex to identify media information, should be posix path. Use single quotes for the strings.
movie = [
	# '.*/(?P<name>.+?) \((?P<year>[0-9]{4})\).*',  # matches /a/b/Taxi Driver (1976).mkv
]
episode = [
	# '.*/(?P<title>.+?) \[[0-9]{3,4}p\]/(?P<episode>\d+) - (?P<episode_title>.*)\.[a-z]{3,4}',  # matches "/a/b/One Punch Man [1080p]/01 - Return of the Hero.mkv"
	# '.*/(?P<title>.+?)\s*?(\[[0-9]{3,4}p\])?/(S|Season)\s?(?P<season>\d+)/(?P<episode>\d+).*',  # matches "/a/b/Mob Psycho 100/Season 2/01 - Ripped Apart ~Someone Is Watching~.mkv"
]

[players]
monitored = ['mpchc', 'mpv']  # players to be monitored. Allowed: 'mpcbe', 'mpchc', 'mpv', 'plex', 'vlc'
skip_interval = 5  # min percent jump to consider for scrobbling to trakt

[players.mpcbe]  # enable web interface from options
ip = "localhost"
port = "13579"  # from Options -> Player -> Web Interface -> Listen on port  (ensure it is ticked) 
poll_interval = 10  # in seconds. How frequently the monitor should check for player update.

[players.mpchc]  # enable web interface from options
ip = "localhost"
port = "13579"  # if both mpchc and mpcbe are to be monitored, then ensure that their ports are different
poll_interval = 10  # in seconds

[players.vlc]  # enable web interface from options
ip = "localhost"
port = "auto-detect"  # set from Preferences -> All -> Input/Codecs -> HTTP Server Port
password = "auto-detect"  # set from Preferences -> All -> Interface -> Main Interfaces -> Lua -> Lua HTTP Password
poll_interval = 10  # in seconds. How frequently the monitor should check for player update.

[players.mpv]  # enable the JSON IPC server. Either via cmd line arg (eg: --input-ipc-server=\\.\pipe\mpvpipe), or in mpv.conf file
ipc_path = 'auto-detect'  # if auto-detect enabled, ensure it is set in mpv.conf file

[players.plex]
ip = "localhost"  # IP of the plex server. Only supports http for now.
port = 32400
login = "login"
password = "password"
poll_interval = 10  # in seconds. How frequently the monitor should check for player update.
