[fileinfo]  # if defined, only files from these directories will be scrobbled
whitelist = [
	"/path/to/movies_folder",
	"/path/to/videos_folder"
]

[fileinfo.include_regexes]
# movie = [".*/(?P<name>.+?) \\((?P<year>[0-9]{4})\\).*",]
episode = [".*/(?P<title>.+?) \\[[0-9]{3,4}p\\]/(?P<episode>\\d+) - (?P<episode_title>.*)\\.[a-z]{3,4}"]

[players]
priorities = ['mpchc', 'mpv', 'vlc']

[players.mpchc]
ip = "localhost"
port = "13579"
poll_interval = 10

[players.vlc]
ip = "localhost"
port = "8080"
password = "password"
poll_interval = 10

[players.mpv]
ipc_path = "\\\\.\\pipe\\mpvpipe"
# ipc_path = "/tmp/mpvsocket"
