[fileinfo]  # if defined, only files from these directories will be scrobbled
whitelist = [
	"/path/to/movies_folder",
	"/path/to/videos_folder"
]

[fileinfo.include_regexes]  # custom regex to identify media information, should be posix path
# movie = [".*/(?P<name>.+?) \\((?P<year>[0-9]{4})\\).*",]
episode = [".*/(?P<title>.+?) \\[[0-9]{3,4}p\\]/(?P<episode>\\d+) - (?P<episode_title>.*)\\.[a-z]{3,4}"]

[players]  # list the required players here, decreasing order of priority
monitored = ['mpcbe', 'mpchc', 'mpv', 'vlc']

[players.mpcbe]  # enable web interface from options
ip = "localhost"
port = "13579"
poll_interval = 10

[players.mpchc]  # enable web interface from options
ip = "localhost"
port = "13579"
poll_interval = 10

[players.vlc]  # enable web interface from options
ip = "localhost"
port = "8080"
password = "password"
poll_interval = 10

[players.mpv]  # enable the JSON IPC server
ipc_path = "\\\\.\\pipe\\mpvpipe"  # windows
# ipc_path = "/tmp/mpvsocket"  # unix
